Algoritmo "soma"
//  
//  

Var
   soma, casa1, comida1, extras, dinheiro1 : inteiro

   
   
Inicio
      escreva("digite a primeira casa")
      leia(casa1)
      

      escreval("digite a primeira comida")
      leia(comida1)
      
      escreval("digite a primeira extras")
      leia(extras)
      
      escreval("digite o primeiro dinheiro")
      leia(dinheiro1)
      
      soma <- dinheiro1 - casa1 - comida1 - extras
      
      escreval(soma)
      
      fimalgoritmo